baseURL = 'https://hhkit.dev/'
languageCode = 'en-us'
theme = 'hugo-goa'

author = 'Ivan Ho'
title = "Hivan, it's... IVaN!"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
author = "Ivan Ho"
intro = 'compilers ⋅ graphics ⋅ gamedev ⋅ education'
description = 'Here to help you help us help us all!'
authorimage = "avatar.svg"
dateformat = '2006/01/02'

[params.meta]
favicon = false

[params.social]
github = "hhkit"
linkedin = "hohkivan"
email = "ivan.ho@cl.cam.ac.uk"

[params.extra]
copyright = "© 2025. Ivan Ho. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true


[[menu.main]]
name = "about"
identifier = "about"
weight = 100
url = "about"

[[menu.main]]
name = "now"
weight = 200
identifier = "now.md"
url = "now"